import { HOKEY } from "./messages/index.js";
export const DESCRIPTION_MESSAGE_SUFFIX = "_description";
export const HINT_MESSAGE_SUFFIX = DESCRIPTION_MESSAGE_SUFFIX;
export const accountLocale = (account, browserLocale, anonLocale) => HOKEY.accountLocale(account, browserLocale, anonLocale);
export const currentLocaleForAccount = (account, browserLocale, anonLocale) => HOKEY.currentLocaleForAccount(account, browserLocale, anonLocale);
export const localeMessagesForAccount = (account, browserLocale, anonLocale) => HOKEY.localeMessagesForAccount(account, browserLocale, anonLocale);
export const localeEmoji = (locale) => HOKEY.localeEmoji(locale);
export const stopWords = () => HOKEY.stopWords();
export const capitalize = (s) => s && s.length > 0 ? s.substring(0, 1).toUpperCase() + s.substring(1) : "";
export const uncapitalize = (s) => s && s.length > 0 ? s.substring(0, 1).toLowerCase() + s.substring(1) : "";
